version: '3'

services:
  chillbot:
    container_name: chillbot
    build: ./
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./logs:/chillbot/logs
    # command: echo $TZ > /etc/timezone
